spring.application.name=Kaoto_Intergrations

camel.springboot.main-run-controller=true
logging.level.org.apache.camel=INFO
logging.level.org.apache.camel.main=DEBUG

#ActiveMQ
spring.activemq.broker-url=tcp://localhost:61616
spring.activemq.user=admin
spring.activemq.password=admin

#MongoDb
#spring.data.mongodb.uri=mongodb://localhost:27017

#Then control execution using
#spring.profiles.active=xml
#camel.springboot.routes-include-pattern=classpath:xml/*.xml
camel.main.routes-include-pattern=classpath:Kaoto/yaml/mail.camel.yaml
#Disable Route Discovery
#camel.springboot.routes-collector-enabled=false
#camel.component.http.trust-all-certificates=true
#camel.component.http.x509-hostname-verifier=NoopHostnameVerifier
slack.webhook.url=https://hooks.slack.com/services/XXX/YYY/ZZZ
#Mail
#mail.host=smtp.gmail.com
#mail.port=465
#mail.username=jayanthilaharikatta@gmail.com
#mail.password=hvqrilqibxvjfnok
#mail.smtp.auth=true
#mail.smtp.starttls.enable=true
#mail.debug=true

#resend.api.key=re_AJLuJwFG_Lz3Y7SacSQhtvFjsUVMDau7Q
#
#alert.to.email=laharijayanthi10@gmail.com
#alert.from.email=order@resend.com

