spring.application.name=Kaoto_Intergrations

camel.springboot.main-run-controller=true
logging.level.org.apache.camel=INFO
logging.level.org.apache.camel.main=DEBUG

#ActiveMQ
spring.activemq.broker-url=tcp://localhost:61616
spring.activemq.user=admin
spring.activemq.password=admin

#MongoDb
#spring.data.mongodb.uri=mongodb://localhost:27017

#Then control execution using
spring.profiles.active=yaml
#camel.springboot.routes-include-pattern=classpath:xml/*.xml
camel.main.routes-include-pattern=classpath:yaml/*.yaml
#Disable Route Discovery
#camel.springboot.routes-collector-enabled=false

#Mail
mail.host=smtp.gmail.com
mail.port=587
mail.username=jayanthilaharikatta@gmail.com
mail.password=hvqr ilqi bxvj fnok

