<?xml version="1.0" encoding="UTF-8"?>
<!-- This file is generated by Kaoto DataMapper. Do not edit. -->
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="3.0" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:fn="http://www.w3.org/2005/xpath-functions">
    <xsl:output method="text" indent="yes"/>
    <xsl:variable name="mapped-xml">
        <map xmlns="http://www.w3.org/2005/xpath-functions">
            <string key="orderNumber">
                <xsl:value-of select="/fn:map/fn:string[@key='salesOrderId']"/>
            </string>
            <string key="customerNumber">
                <xsl:value-of select="/fn:map/fn:map[@key='customer']/fn:string[@key='customerId']"/>
            </string>
            <string key="customerName">
                <xsl:value-of select="/fn:map/fn:map[@key='customer']/fn:string[@key='name']"/>
            </string>
            <string key="formattedDate">
                <xsl:value-of select="/fn:map/fn:string[@key='orderDate']"/>
            </string>
            <string key="amount">
                <xsl:value-of select="/fn:map/fn:number[@key='totalAmount']"/>
            </string>
            <string key="currencyCode">
                <xsl:value-of select="/fn:map/fn:string[@key='currency']"/>
            </string>
        </map>
    </xsl:variable>
    <xsl:template match="/">
        <xsl:value-of select="xml-to-json($mapped-xml)"/>
    </xsl:template>
</xsl:stylesheet>