spring.application.name=Kaoto_Intergrations

server.port=8089
camel.springboot.main-run-controller=true
camel.springboot.stream-caching-enabled=true

logging.level.org.apache.camel=INFO
logging.level.org.apache.camel.main=DEBUG

# ActiveMQ
spring.activemq.broker-url=tcp://localhost:61616
spring.activemq.user=admin
spring.activemq.password=admin

#MongoDb
spring.data.mongodb.uri=mongodb://localhost:27017

# Mail Configuration
spring.mail.host=smtp.gmail.com
#spring.mail.port=587
spring.mail.username=jayanthilaharikatta@gmail.com
spring.mail.password=hvqrilqibxvjfnok
spring.mail.port=465
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Alert Mail
alert.to.email=laharijayanthi10@gmail.com

# Routes
camel.main.routes-include-pattern=classpath:Kaoto/yaml/xml-trg-delivery-monitor.yaml

# Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# Prometheus
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true


#slack.webhook.url=https://hooks.slack.com/services/XXX/YYY/ZZZ

#resend.api.key=re_AJLuJwFG_Lz3Y7SacSQhtvFjsUVMDau7Q
#alert.to.email=laharijayanthi10@gmail.com
#alert.from.email=order@resend.com

# Route file
#camel.main.routes-include-pattern=classpath:camel/*.yaml
